#pragma once
// Defaults in <SDK>/config/sdk_config.h

#define APP_TIMER_ENABLED 1
#define BLE_ADVERTISING_ENABLED 1
#define BUTTON_ENABLED 1
#define FDS_ENABLED 1
#define GPIOTE_ENABLED 1
#define NRF_BALLOC_ENABLED 1
#define NRF_BLE_CONN_PARAMS_ENABLED 1
#define NRF_BLE_GATT_ENABLED 1
#define NRF_CLI_ECHO_STATUS 1
#define NRF_CLI_ENABLED 1
#define NRF_CLI_LOG_BACKEND 1
#define NRF_CLI_RTT_ENABLED 1
#define NRF_FPRINTF_ENABLED 1
#define NRF_FSTORAGE_ENABLED 1
#define NRF_LOG_ENABLED 1
#define NRF_LOG_ERROR_COLOR 2
#define NRF_LOG_USES_COLORS 1
#define NRF_LOG_WARNING_COLOR 4
#define NRF_QUEUE_ENABLED 1
#define NRF_SDH_BLE_ENABLED 1
//#define NRF_SDH_BLE_GATTS_ATTR_TAB_SIZE 1408
#define NRF_SDH_BLE_PERIPHERAL_LINK_COUNT 1
#define NRF_SDH_BLE_VS_UUID_COUNT 1
#define NRF_SDH_ENABLED 1
#define NRF_SDH_SOC_ENABLED 1
#define NRF_SECTION_ITER_ENABLED 1
#define NRF_STRERROR_ENABLED 1
#define PEER_MANAGER_ENABLED 1
#define NRF_SDH_BLE_GATT_MAX_MTU_SIZE 250
#define SEGGER_RTT_CONFIG_DEFAULT_MODE 1 //TRIM

#define CLOCK_ENABLED 1
#define NFC_AC_REC_ENABLED 1
#define NFC_BLE_OOB_ADVDATA_ENABLED 1
#define NFC_BLE_PAIR_LIB_ENABLED 1
#define NFC_BLE_PAIR_MSG_ENABLED 1
#define NFC_CH_COMMON_ENABLED 1
#define NFC_EP_OOB_REC_ENABLED 1
#define NFC_HS_REC_ENABLED 1
#define NFC_LE_OOB_REC_ENABLED 1
#define NFC_NDEF_MSG_ENABLED 1
#define NFC_NDEF_RECORD_ENABLED 1
#define NFC_PAIRING_MODE 4 // NFC_PAIRING_MODE_GENERIC_OOB
#define NFC_T2T_HAL_ENABLED 1
#define RNG_ENABLED 1

#define NRF_GFX_ENABLED 1
#define NRF_SPI_DRV_MISO_PULLUP_CFG 1
#define NRF_SPI_MNGR_ENABLED 1
#define SPI0_ENABLED 1
#define SPI0_USE_EASY_DMA 0
#define SPI_ENABLED 1

#ifdef DEBUG_NRF
#define NRF_LOG_DEFERRRED 0
#define NRF_LOG_DEFAULT_LEVEL 4 //Debug
#define NRF_BLE_PAIR_LIB_LOG_ENABLED 1
#define HAL_NFC_CONFIG_LOG_ENABLED 1
#endif
